-- CreateTable
CREATE TABLE `SPVRelation` (
    `id` VARCHAR(191) NOT NULL,
    `spvId` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `SPVRelation` ADD CONSTRAINT `SPVRelation_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SPVRelation` ADD CONSTRAINT `SPVRelation_spvId_fkey` FOREIGN KEY (`spvId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
